server:
  port: 8081
spring:
  application:
    name: clases

  # ESTO DEBE IR DENTRO DE "spring:"
  datasource:
    url: jdbc:mysql://localhost:3306/ingenieria_web
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update # Crea/actualiza tablas automáticamente
    show-sql: true # Muestra SQL en consola (útil para aprender)
    properties:
      hibernate:
        format_sql: true # SQL formateado (más legible)
        dialect: org.hibernate.dialect.MySQL8Dialect

  cache:
    type: redis # Usa Redis como backend de caché
    redis:
      time-to-live: 600000 # TTL default: 10 minutos (en milisegundos)
  data:
    redis:
      host: localhost
      port: 6379
      # password: tu_password # Solo si configuraste requirepass

  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASS}
    virtualhost: ${RABBIT_VIRTUAL_HOST}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000

# TUS CONFIGURACIONES PERSONALIZADAS AFUERA DE "spring:"
espocrm:
  base-url: http://localhost:8082
  api-key: ${ESPO_API_KEY}

woocommerce:
  base-url: ${WORDPRESS_URL}
  consumer-key: ${WOO_CONSUMER_KEY}
  consumer-secret: ${WOO_CONSUMER_SECRET}

wordpress:
  url: ${WORDPRESS_URL_POSTS}
  base-url: ${WORDPRESS_URL}
  username: ${WORDPRESS_USER}
  app-password: ${WORDPRESS_APP_PASSWORD}
app:
  email:
    from: "cesar.andrade@irya.xyz"
    subject: "2024010479|César Alfredo Andrade"

#Internas
#user
# admin
#pass
# Cvoq Nwj9 cAHw fzVm ZOWv xVON
#Clave del cliente
# ck_dc8b7d7e40102108764920c612853eadd0bd3d18
#Clave secreta del cliente
# cs_78f1d575a5389241a90ffc04eb29be2cded6a1d2